apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  labels:
    app: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: flaskapp:minikube
        ports:
          - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
  labels:
    app: flaskapp
spec:
  type: ClusterIP 
  selector:
    app: flaskapp
  ports: 
  - port: 5000
    targetPort: 5000